### ISSUE TITLE
TypeError: Cannot read property 'open' of undefined

### ISSUE THREAD

**Issue by PrantikMondal** [douglasjunior/react-native-recaptcha-that-works#1]
My code is: 

send = () => {
        console.log('send!');
        **this.recaptcha.open(); // Error is showing here to open**
    }

    onVerify = token => {
        console.log('success!', token);
    }

    onExpire = () => {
        console.warn('expired!');
    }

    render() {
        return (
            <View>
                <Recaptcha
                    ref={ref => this.recaptcha = ref}
                    siteKey="<your-recaptcha-public-key>"
                    baseUrl="http://my.domain.com"
                    onVerify={this.onVerify}
                    onExpire={this.onExpire}
                    size="invisible"
                />
                <Button title="Send" onPress={this.send} />
            </View>
        )
    }

**Comment by douglasjunior** [comment]
Please take a look at the [Sample project](https://github.com/douglasjunior/react-native-recaptcha-that-works/blob/master/Sample/src/App.js) or in the [Snack showcase](https://snack.expo.io/@douglasjunior/a6aed2).
