### ISSUE TITLE
Captcha without modal view

### ISSUE THREAD

**Issue by Mj835** [douglasjunior/react-native-recaptcha-that-works#11]
I want to implement this captcha but it should view directly no need for that modal view. Please help me its urgent work request.

**Comment by jazibabdullah1** [comment]
Hi @Mj835,
did you find any solution? I am facing the same problem.

**Comment by troZee** [comment]
You can just remove the modal root view and then it should be fine.

**Comment by douglasjunior** [comment]
The modal is used to display the WebView in fullscreen mode, if you dont use a Modal you need to display the webview directly in the middle of your components.

If it doesn't go full screen, the recaptcha probably won't fit on the screen for the user to solve the challenge.

**Comment by Rushiraj-karm** [comment]
can you please give me example to show only webview without Modal.

**Comment by douglasjunior** [comment]
> can you please give me example to show only webview without Modal.

Today, it is not possible.

**Comment by usharmaMobileDevTeam** [comment]
I removed modal in nodemodules=>recatcha.js. Fixed for me.

Please provide a props to for avoiding modal. in library.

Thanks

**Comment by douglasjunior** [comment]
Without modal, the webview will be displayed inline, in the middle of others screen components.

I can't guarantee that there will be space, or that the webview will render all the content as expected.
