### ISSUE TITLE
Using "invisible" size blocks the UI

### ISSUE THREAD

**Issue by natioskar** [douglasjunior/react-native-recaptcha-that-works#14]
Hey! thanks for this lib thats really works 🚀 

I'm using the invisible, but found out that the Modal block the whole UI until it's not visible the token verified.
in the current implementation is there a way to mitigate this behaviour?

Playing around I found out that without rendering the Modal (just the web-view) I can still get it to work

Thanks!

**Comment by douglasjunior** [comment]
The problem is that the "invisible" doesn't always work.

If the user needs to solve the challenge, there won't be enough space as the challenge window covers most of the screen. 

![image](https://user-images.githubusercontent.com/1512341/127852471-dcd2e442-e705-4bbe-9a3a-b8083051d4bd.png)

**Comment by douglasjunior** [comment]
Duplicated from #11
