### ISSUE TITLE
invisible

### ISSUE THREAD

**Issue by from0toweb** [douglasjunior/react-native-recaptcha-that-works#15]
hi! Can you do this? so that when the property is invisible, the captcha icon in the right, bottom corner is not visible. You can give a webview component, for example, flex = 0. And the background Loading component, darkening. Users are annoyed by this banner

**Comment by from0toweb** [comment]
it would be necessary to set the default color for the indicator for android, otherwise it is not visible

**Comment by douglasjunior** [comment]
I think that is better to create a Prop to pass a custom ActivityIndicator.

**Comment by victor-cui-brigit** [comment]
I would like a way to do this too! When you say "create a prop to pass a custom ActivityIndicator", is that something we can do using the library or would we have to modify this repo's source code?

**Comment by douglasjunior** [comment]
Done in 1.2.0 https://github.com/douglasjunior/react-native-recaptcha-that-works/releases/tag/1.2.0

**Comment by victor-cui-brigit** [comment]
could you please give an example of how to use the latest version (1.2.0) to hide the captcha icon on the bottom right corner? Would I pass a custom webview prop, custom modal prop, or a custom loading component?

**Comment by Sowed** [comment]
> could you please give an example of how to use the latest version (1.2.0) to hide the captcha icon on the bottom right corner? Would I pass a custom webview prop, custom modal prop, or a custom loading component?

@victor-cui-brigit , using the `hideBadge` prop alongside `size=hidden`

**Comment by douglasjunior** [comment]
Take a look at the docs section: https://github.com/douglasjunior/react-native-recaptcha-that-works#props

![image](https://user-images.githubusercontent.com/1512341/180230871-ec6ba09f-11d2-424b-9602-254dcb8460cb.png)
