### ISSUE TITLE
How to handle onExpire event

### ISSUE THREAD

**Issue by victor-cui-brigit** [douglasjunior/react-native-recaptcha-that-works#19]
Is it expected to open the recaptcha again with `recaptcha.current?.open()` on the onExpire callback? If not, how is the expiration usually handled?

**Comment by douglasjunior** [comment]
onExpire is just a callback to notify you.

Google says: **Optional. The name of your callback function, executed when the reCAPTCHA response expires and the user needs to re-verify.**

Docs: https://developers.google.com/recaptcha/docs/display#render_param
