### ISSUE TITLE
Remove screen fading momentarily to black

### ISSUE THREAD

**Issue by victor-cui-brigit** [douglasjunior/react-native-recaptcha-that-works#20]
Right before the captcha icon loads in the bottom-right corner of the react native app (for both normal and invisible mode), the screen changes momentarily to black. Is there a way to avoid this?

**Comment by douglasjunior** [comment]
You are talking about the fade effect when modal opens?

| Normal | Invisible |
| - | - |
| <img src='https://raw.githubusercontent.com/douglasjunior/react-native-recaptcha-that-works/master/screenshots/normal.gif' width='240' /> | <img src='https://raw.githubusercontent.com/douglasjunior/react-native-recaptcha-that-works/master/screenshots/invisible.gif' width='240' /> |

**Comment by victor-cui-brigit** [comment]
yes I'm talking about the fade momentarily to a darker screen. I would like to remove the fade entirely

**Comment by douglasjunior** [comment]
You can change the background color with styles.

```jsx
<Recaptcha
    style={{ backgroundColor: 'transparent' }}
/>
```

Docs: https://github.com/douglasjunior/react-native-recaptcha-that-works#props

**Comment by victor-cui-brigit** [comment]
this worked, thanks!
