### ISSUE TITLE
iOS: Invisible reCaptcha show Image grid

### ISSUE THREAD

**Issue by dcharya** [douglasjunior/react-native-recaptcha-that-works#22]
@douglasjunior I am trying to implement invisible reCaptcha. On iOS I notice on first attempt, App display image grid.

```
<Recaptcha
        ref={recaptcha}
        siteKey="<Site-Key>"
        baseUrl="https://my.nasdaq.com"
        onVerify={onVerify}
        onExpire={onExpire}
        size="invisible"
/>
```

**Comment by douglasjunior** [comment]
By "image grid" do you mean the challenge window?

![image](https://user-images.githubusercontent.com/1512341/148204112-3568027f-370b-4253-b885-ebe81edb78ee.png)

If yes, the challenge window can appear in any "type", this is calculated by recaptcha.

**Comment by rohithnair1996** [comment]
Having the same issue. Any solution ?
