### ISSUE TITLE
v3 Invisible - ActivityIndicator 

### ISSUE THREAD

**Issue by Rakee08** [douglasjunior/react-native-recaptcha-that-works#24]
On recaptcha.current.open();
Along with activity indicator recaptcha icon coming on right bottom corner, which is looking odd.

**Comment by douglasjunior** [comment]
This is how reCaptcha invisible should works.

https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-badge.-what-is-allowed

**Comment by pierroo** [comment]
Weird, how come this other plugin doesn't show the badge?
https://www.npmjs.com/package/react-native-recaptcha-v3

=> are they actually playing against google ToS for recaptcha?

**Comment by douglasjunior** [comment]
> You are allowed to hide the badge as long as you include the reCAPTCHA branding visibly in the user flow. Please include the following text:

```html
 This site is protected by reCAPTCHA and the Google
    <a href="https://policies.google.com/privacy">Privacy Policy</a> and
    <a href="https://policies.google.com/terms">Terms of Service</a> apply.
```

From: https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-badge.-what-is-allowed

I think we can add prop `hideBadge=true/false` and it's up to you to follow the rules.

**Comment by pierroo** [comment]
Thank you for your answer.
So I'd say this other plugin is not really mentioning that and it could be harmful to some other developers.

I will move on to using yours, that actually seems to be working much better, thank you!

**Comment by douglasjunior** [comment]
Added `hideBadge` prop.

https://github.com/douglasjunior/react-native-recaptcha-that-works/releases/tag/1.3.1
