### ISSUE TITLE
Cannot close modal after verifying Recaptcha in IOS

### ISSUE THREAD

**Issue by ngxuancam** [douglasjunior/react-native-recaptcha-that-works#25]
-  "react-native": "0.66.3",
-  "react-native-webview": "^11.17.0",
-  "react-native-recaptcha-that-works": "^1.2.0",
-  Version: Iphone 12 Pro Max - IOS 14.5
-  Cannot close modal after verifying recaptcha
-  Android is fine but IOS is not work

Note: I used ref to close but not work

**Comment by douglasjunior** [comment]
Please, provide a reproducible demo, like this https://snack.expo.dev/@douglasjunior/react-native-recaptcha-that-works
