### ISSUE TITLE
Jest issue

### ISSUE THREAD

**Issue by Zakyyy** [douglasjunior/react-native-recaptcha-that-works#26]
Here is how I implemented Recaptcha in my app
```
import React from 'react';
import RecaptchaV3 from 'react-native-recaptcha-that-works';
import {RECAPTCHA_SECRET, RECAPTCHA_DOMAIN} from '@env';

const Recaptcha = React.forwardRef(({onSuccess}, ref) => {
  const onVerifyRecaptcha = token => {
    onSuccess(token);
  };

  const onExpire = () => {
    console.warn('expired!');
  };
  return (
    <RecaptchaV3
      ref={ref}
      siteKey={RECAPTCHA_SECRET}
      baseUrl={RECAPTCHA_DOMAIN}
      onVerify={onVerifyRecaptcha}
      onExpire={onExpire}
      size="normal"
    />
  );
});

export default Recaptcha;

```

when I run npm test, I get the following error
`React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

Anyone was able to solve this issue or have a mock file for the package.

- What version of React Native?0.66.1
- What version of React Native WebView? 11.2.2
- What version of the library?1.2.0
- iOS/Android version?
- Did the problem happen after updating React Native? no
- Are you using the library for the first time? yes
- It's a bug? Provide a link to a minimal reproduction case.

**Comment by Zakyyy** [comment]
following up on this, I managed to pass the error by creating this mock file react-native-recaptcha-that-works.js inside __mocks__ folder
```
import React from 'react';
import {View} from 'react-native';
const Recaptcha = props => <View {...props} />;
export default Recaptcha;
```

**Comment by douglasjunior** [comment]
I added some tests to the [Sample project](https://github.com/douglasjunior/react-native-recaptcha-that-works/tree/master/Sample/__tests__), but I don't need any mock to make it work.

![image](https://user-images.githubusercontent.com/1512341/166921317-a37fd40b-c0b1-423b-b2f5-42a71beb5469.png)
