### ISSUE TITLE
Fallback to V2

### ISSUE THREAD

**Issue by pierroo** [douglasjunior/react-native-recaptcha-that-works#31]
Hi,

I saw in another thread that the default V3 sometimes falls back to recaptcha V2.
I was unable to reproduce it, but I would like to know:

- is the flow exactly the same?
- does it still trigger onVerify / onLoad / onError etc the same way as V3?
- can the user leave the V2 question modal? what happens if they do?
- if the user is wrong in passing this V2 test, what does it trigger? onError or something else?

Asking since I wouldn't want to have a state "stuck in between" with a loading modal or whatever I put in place for V3 that behaves differently for V2?

Thank you for your help!

**Comment by douglasjunior** [comment]
Sorry, this library dont work with recaptcha v3.

**Comment by pierroo** [comment]
Wait, I'm confused; why is my recaptcha V3 key working then?
And why is the whole process invisible as intended with V3, unlike V2 that asks for questions?
