### ISSUE TITLE
Question: Does this tool help prevent bot tasks from tools like browser stack?

### ISSUE THREAD

**Issue by Sowed** [douglasjunior/react-native-recaptcha-that-works#32]
Hello. I don't know if this is the right place to ask since there is no discussion tab. Apologies in advance.

I am testing this tool with hidden mode (`size=invisible`) and it seems to be working fine in the normal/positive cases. The app opens the ReCaptcha and validates it seamlessly.

The problem is testing the negative cases. The QA team with automated testing bots on [BrowserStack](https://www.browserstack.com/) are able to bypass the captcha verification, and the hidden captcha treats them as real users. (Understandable browser stack might be running on real devices in the backend).

- Was wondering, since this is running in a WebView, how does it deduce user action on a Button outside the WebView?
- Does the hidden captcha detect single button clicks without form elements if automated?

**Comment by douglasjunior** [comment]
> Hello. I don't know if this is the right place to ask since there is no discussion tab. Apologies in advance.

Don't worry.

> Was wondering, since this is running in a WebView, how does it deduce user action on a Button outside the WebView?

We always trusted Google to make sure that reCAPTCHA would do an analysis on the behavior of the webview to make sure it's not a robot.

Something I've noticed during development is that if you solve the captcha too many times, it starts to suspect it's a robot.

> Does the hidden captcha detect single button clicks without form elements if automated?

Invisible mode only runs when the webview is created, so before that it won't detect anything.

If you want, you can try increasing the "security level" of your reCAPTCHA in the console:

![image](https://user-images.githubusercontent.com/1512341/180201610-9891a92b-002b-45c0-8efd-0d181fa9f0a1.png)
