### ISSUE TITLE
Is this Recaptcha V2 or V3?

### ISSUE THREAD

**Issue by pierroo** [douglasjunior/react-native-recaptcha-that-works#33]
I am sorry if this is a duplicate of my other issue #31 , but since it was closed without answer I need to clarify:

Is this library using recaptcha v2 or v3?
You stated in issue 31 that this library doesn't work with recaptcha 3, but then my question remains:

Why is the whole process invisible as intended with V3, unlike V2 that asks for questions?

How come my recapatcha v3 key seems to be working with your plugin; and even the backend v3 checking the score is working as expected when sending your plugin generated token?

So did you mean to say that your library doesn't work with V2 rather than V3?

Thank you for your help!

**Comment by douglasjunior** [comment]
> Why is the whole process invisible as intended with V3, unlike V2 that asks for questions?

I dont know about reCAPTCHA v3 yet, I've never worked with it, if it works it's purely coincidental.

**Comment by pierroo** [comment]
Okay so you confirm your plugin is V2?
Thank you!

Surprising indeed that it both works from the front, AND from the backend when verifying the captcha score!
I will update here if I find anything.

**Comment by douglasjunior** [comment]
> It's not mentioned in your doc but, what are we supposed to put in "baseUrl" when it comes to mobile app?

The domain that you put in the [reCAPTCHA Admin Console](https://www.google.com/recaptcha/admin).

![image](https://user-images.githubusercontent.com/1512341/180231386-b1265c49-026e-4a0b-9b17-0e31b0df508c.png)

> For v3, it should be "com.package.name", and the trick was to add "https://com.package.name/", although in the google console we put com.package.name as domain.

Sorry, I dont know much about reCAPTCHA v3, but remember: this library was created to reCAPTCHA v2 web API, so its not suppose to work as Android native API.

You should configure the reCAPTCHA as you are using in a web page, and not in a mobile app.

**Comment by pierroo** [comment]
This is confusing, why is it called react NATIVE recaptcha then?
I understand it's pure javascript, but still isn't it supposed to work on mobile devices since it's react native library?

**Comment by douglasjunior** [comment]
When I say that don't work as Android native API, I refer to reCaptcha Android native SDK.

reCaptcha is not officially supported on iOS.

This library was created to work with Android AND iOS, so we can't use the Android SDK for this.

The only way is to use an WebView as an workaround, and inside we implement with web API.

Please, read the library source code to understand how it works, and if you have any other relevant question about the library, I'm here to help.
