### ISSUE TITLE
In invisible size, custom domain is not working 

### ISSUE THREAD

**Issue by NensiKasundra** [douglasjunior/react-native-recaptcha-that-works#38]
It's not loading google Captcha with an invisible size. It's working fine with normal size.

  ```
<Recaptcha
                            ref={recaptchaRef}
                            lang="en"
                            siteKey="key"
                            baseUrl={CAPTCHA_CUSTOM_DOMAIN_URL} 
                            size="invisible"
                            theme="light"
                            onLoad={() => console.log('onLoad event')}
                            onClose={() => console.log('onClose event')}
                            onError={(err) => {
                                console.warn('error', err)
                                console.log('onError event')
                            }}
                            onExpire={() => console.log('onExpire event')}
                            onVerify={(token) => {
                                console.log('onVerify event', token)
                                setKey(token)
                            }}
                            hideBadge={true}
                        />
```

- React Native - 0.67.2
- React Native WebView - 11.25.0
- react-native-recaptcha-that-works - 1.3.2 

I really appreciate any help you can provide!

@douglasjunior  @codev0 @gin-melodic @MrHertal

**Comment by douglasjunior** [comment]
It's working fine for me, please provide more info.

**Comment by NensiKasundra** [comment]
Have you checked with the custom domain URL? I'm getting an error as null with invisible size.

**Comment by douglasjunior** [comment]
It's working on DEMO too https://snack.expo.dev/@douglasjunior/react-native-recaptcha-that-works

**Comment by douglasjunior** [comment]
> Have you checked with the custom domain URL? I'm getting an error as null with invisible size.

Take a look https://github.com/douglasjunior/react-native-recaptcha-that-works/issues/34
