### ISSUE TITLE
Unable to close the modal of Recaptcha

### ISSUE THREAD

**Issue by SynoViren** [douglasjunior/react-native-recaptcha-that-works#39]
- RN Version 0.66.4
- Webview Version 11.13.1
- Lib Version 1.3.2
- iOS/Android version? iOS 15
- Did the problem happen after updating React Native? **No**
- Are you using the library for the first time? **Yes**
My Modal is not getting closed after the token is received successfully.

```
  const recaptcha = useRef();
 <Recaptcha
                ref={recaptcha}
                siteKey="my site key"
                baseUrl="my url"
                onVerify={onVerify}
                onExpire={onExpire}
                size="invisible"
            /> 
```
```
const send = () => {
   recaptcha.current.open();
}

const onVerify = token => {
    console.log('success!', token);
    recaptcha.current.close();
}
```
Once on Verify is called. THe modal is not getting closed.

**Comment by douglasjunior** [comment]
It's working in the Snack Demo and others apps that I maintain.

https://snack.expo.dev/@douglasjunior/react-native-recaptcha-that-works

**Comment by 14850842** [comment]
I have this issue in the simulator on Expo Go but not in Expo go on the physical device.
