### ISSUE TITLE
I am not getting any response

### ISSUE THREAD

**Issue by Spyy004** [douglasjunior/react-native-recaptcha-that-works#40]
What is the baseUrl prop? The invisible captcha don't seem to work for me. I have added the component but I am not recieving any token.

**Comment by douglasjunior** [comment]
As described in the docs, `baseUrl` is the URL (domain) configured in the reCAPTCHA console setup. 

Se also https://github.com/douglasjunior/react-native-recaptcha-that-works/issues/38 and https://github.com/douglasjunior/react-native-recaptcha-that-works/issues/34.

**Comment by Spyy004** [comment]
This is my current code. Remember, I am using class based component. 

![Screenshot from 2023-03-31 17-18-17](https://user-images.githubusercontent.com/54628130/229112310-0b0bf189-3001-4450-841a-6970d3d4b0b0.png)

When I render the page, nothing happens. The SITE_KEY that I am using is created in my enterprise account for WEB

**Comment by Spyy004** [comment]
Okay so i got it working but i am not getting any captcha verification. Just get a blank on open alert, then an empty on-error window. The error message is null

**Comment by yaminichhabra** [comment]
@Spyy004 - did it work for you ? I am not even getting the header component on the screen

**Comment by douglasjunior** [comment]
Please guys, just follow the demo

https://snack.expo.dev/@douglasjunior/react-native-recaptcha-that-works
