### ISSUE TITLE
Blocking the UI

### ISSUE THREAD

**Issue by halid96** [douglasjunior/react-native-recaptcha-that-works#42]
When it is generating a token, its blocking the UI. The UI becomes unresponsive to touches and scrolling for about 1 second. This happens on both iOS and Android.

Please could you make this non-blocking? Thank you in advance.

This is my setup:

```
                    <View style={{ display: 'none' }}>
                        <Recaptcha
                            style={{ display: 'none' }}
                            ref={recaptcha}
                            loadingComponent={<></>}
                            siteKey="6LcsO5sUAAAGDSWMFSKLWDnP1DjHjaZN"
                            baseUrl="https://www.trollflix.com"
                            onVerify={onVerify}
                            size="invisible"
                            hideBadge={true}
                            modalProps={{ visible: false, animationType: 'none', transparent: true, supportedOrientations: ['landscape-right'], statusBarTranslucent: true }}
                        />
                    </View>
```

**Comment by douglasjunior** [comment]
No, it is not possible to make "no blocking" UI, this is a required behavior.

The UI is blocked because is covered by a Modal component to render the WebView properly.

**Comment by halid96** [comment]
> No, it is not possible to make "no blocking" UI, this is a required behavior.
> 
> The UI is blocked because is covered by a Modal component to render the WebView properly.

WebView is for the web, actually am asking for an iOS app. Recaptcha v3 suppose to not block the UI, also why rendering something actually? Recaptcha V3 is invisible so you don't need even a modal in my opinion.

**Comment by douglasjunior** [comment]
This library uses the Web version of reCaptcha with WebView.

Please checkout the Readme.
