### ISSUE TITLE
Chrome Certificate Transparency log list v2 turndown

### ISSUE THREAD

**Issue by SynoViren** [douglasjunior/react-native-recaptcha-that-works#44]
My app got this warning from playstore:
Firstly, gstatic log_list.json will start returning 404 on 2023-06-07 around 10AM UTC+1.

I assume that this lib uses the above URL? Any solution to be implemented?

**Comment by douglasjunior** [comment]
Can you copy the complete message?

And if possible, any link to Google documentation with instructions to migrate.

**Comment by douglasjunior** [comment]
The Google documentation still point to `https://www.google.com/recaptcha/api.js`: 

- Default: https://developers.google.com/recaptcha/docs/display?hl=en
- Enterprise: https://cloud.google.com/recaptcha-enterprise/docs/using-features?hl=en

Which we do here: 

https://github.com/douglasjunior/react-native-recaptcha-that-works/blob/c63f195130d7cb4c1e04ba0b89f617b6e4243f7b/src/get-template.js#L33-L35

**Comment by SynoViren** [comment]
Should it be concerning? Also, does it suggest internal migration to v3.

**Comment by douglasjunior** [comment]
I really don't know, I tried searching for "recaptcha v2 deprecation" and found nothing.
