### ISSUE TITLE
Facing issue inside modals

### ISSUE THREAD

**Issue by cs-ashiqu** [douglasjunior/react-native-recaptcha-that-works#45]
I am facing issue while trying to open captcha inside modals. Captcha is not opening. 
@douglasjunior Can you help to solve this issue?

**Comment by douglasjunior** [comment]
This library uses the native [Modal](https://reactnative.dev/docs/modal) from React Native.

If you are using a native modal to render Recaptcha you may have a problem because opening a Modal over another Modal can be a trick.
