### ISSUE TITLE
Encountering 'onError' Triggered Issue with reCAPTCHA: Help Needed!

### ISSUE THREAD

**Issue by beingArkReal** [douglasjunior/react-native-recaptcha-that-works#46]
- React Native version: 0.72.0
- React Native WebView version: 13.2.2
- Library version: 1.3.2
- Platform: Android
- Problem occurred after updating React Native: Yes
- First time using the library: No

**Comment by douglasjunior** [comment]
Please, provide more info about the problem that you are encountering, the complete error with stack trace, code snippet, etc.

If possible, reproduce the problem following the online demo and share the link with us https://snack.expo.dev/@douglasjunior/react-native-recaptcha-that-works
