### ISSUE TITLE
Support of React Native Web ? 

### ISSUE THREAD

**Issue by 6mo** [douglasjunior/react-native-recaptcha-that-works#47]
Thank you for this awesome lib that really works :)

The main readme doesn't mention the support of react-native-web .
is this planned in the futur ?

**Comment by douglasjunior** [comment]
For web you can use the https://github.com/douglasjunior/react-recaptcha-that-works

It's a very similar API, but has some little differences.

Sou you can create two Recaptcha components in yout app, like:

```
my/components/path/Recaptcha.native.js
my/components/path/Recaptcha.web.js
```
