### ISSUE TITLE
Vertically center

### ISSUE THREAD

**Issue by iam-ben** [douglasjunior/react-native-recaptcha-that-works#48]
I tried to vertically center the Recaptcha challenge window but failed so far, it always stuck on top. On some newer iPhone model (looks like start from iPhone 14 Pro Max and above) it even overlap with the camera. 

Tried to wrap with SafeAreaView but didn't work since the library is using a modal and it looks like it occupies the whole screen. Any suggestions what is the easiest way to accomplish this? Wonder wrapping the header component, the web view, and the footer component inside a View and then making the style overridable might help.

<img width="357" alt="Screenshot 2023-10-18 at 11 58 13 AM" src="https://github.com/douglasjunior/react-native-recaptcha-that-works/assets/56574090/d4416da9-d015-4bda-b678-aa1a847e0c4b">

- What version of React Native? 0.72
- What version of React Native WebView? 13.3.1
- What version of the library? 1.3.2
- iOS/Android version? tested on iOS
- Did the problem happen after updating React Native? No
- Are you using the library for the first time? No
- It's a bug? Provide a link to a minimal reproduction case.

**Comment by douglasjunior** [comment]
Unfortunately, this is how Google renders the reCAPTCHA dialog on mobile browsers.

You can try to inject JS to create CSS code inside the webview and force the wanted position, but I can't guarantee that it will work forever.

Example:

```ts
<Recaptcha
   webViewProps={{
       injectedJavaScript: `
           // your javascript code here
       `
   }}
/>
```

Reference: https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#injectedjavascript

**Comment by w1ll-dev** [comment]
[iam-ben](https://github.com/iam-ben) You can also use `style` prop to put the challenge inside a safe area using a margin.

**Comment by douglasjunior** [comment]
Good option @w1ll-dev.

**Comment by kashee-lv** [comment]
Facing same issue but @w1ll-dev top part is not looking blur as in bottom

**Comment by w1ll-dev** [comment]
> Facing same issue but @w1ll-dev top part is not looking blur as in bottom 

Can you show me the code and a screenshot?

**Comment by kashee-lv** [comment]
@w1ll-dev please check the screenshot it not covering to the whole screen 


` const insets = useSafeAreaInsets();

const styles = useMemo(
  () => ({
    marginTop: insets.top,
  }),
  [insets.top],
);


<SafeAreaView style={{flex: 1, backgroundColor: colors.background}}>
    <View style={{flex: 1}}>
      <Recaptcha
        ref={recaptcha}
        siteKey=""
        baseUrl="https://www.google.com/"
        onVerify={onVerify}
        onExpire={onExpire}
        style={styles}
      />
    </View>
</SafeAreaView>`


![image1](https://github.com/douglasjunior/react-native-recaptcha-that-works/assets/102792352/d49c3d88-0e5f-4481-bf06-8b18a6c01f30)
![image2](https://github.com/douglasjunior/react-native-recaptcha-that-works/assets/102792352/568942ca-c612-4751-948f-89f7586743d5)

**Comment by w1ll-dev** [comment]
got it > kashee-lv, my approach just fix the status bar cover problem.

**Comment by dryusha** [comment]
I encountered a similar issue and was able to resolve it with the following approach:

```
const insets = useSafeAreaInsets();

webViewProps={{
  injectedJavaScript: `
    const interval = setInterval(() => {
      const iFrames = document.querySelectorAll('iframe');
      let lastDivWithIFrame = null;

      iFrames.forEach((iframe) => {
        const parentDiv = iframe.parentElement;

        if (parentDiv.tagName.toLowerCase() === 'div') {
          const zIndex = window.getComputedStyle(parentDiv).zIndex;
          const width = parentDiv.style.width;

          if (zIndex === "2000000000" && width.includes('px')) {
            lastDivWithIFrame = parentDiv;
          }
        }
      });

      if (lastDivWithIFrame) {
        lastDivWithIFrame.style.marginTop = "${insets.top}px";
        clearInterval(interval);
      }
    }, 500);
  `,
}}
```

This script continuously checks for <iframe> elements within <div> containers that match specific conditions (i.e., zIndex of "2000000000" and a width defined in pixels). Once the target element is identified, it adjusts the marginTop property of the parent <div> to match the top inset value provided by useSafeAreaInsets, and then clears the interval to stop further execution.

This approach resolved the issue in my case. I hope it helps others facing similar challenges.

**Comment by JCYDigitalinnov** [comment]
> I encountered a similar issue and was able to resolve it with the following approach:
> 
> ```
> const insets = useSafeAreaInsets();
> 
> webViewProps={{
>   injectedJavaScript: `
>     const interval = setInterval(() => {
>       const iFrames = document.querySelectorAll('iframe');
>       let lastDivWithIFrame = null;
> 
>       iFrames.forEach((iframe) => {
>         const parentDiv = iframe.parentElement;
> 
>         if (parentDiv.tagName.toLowerCase() === 'div') {
>           const zIndex = window.getComputedStyle(parentDiv).zIndex;
>           const width = parentDiv.style.width;
> 
>           if (zIndex === "2000000000" && width.includes('px')) {
>             lastDivWithIFrame = parentDiv;
>           }
>         }
>       });
> 
>       if (lastDivWithIFrame) {
>         lastDivWithIFrame.style.marginTop = "${insets.top}px";
>         clearInterval(interval);
>       }
>     }, 500);
>   `,
> }}
> ```
> 
> This script continuously checks for <iframe> elements within
> 
> containers that match specific conditions (i.e., zIndex of "2000000000" and a width defined in pixels). Once the target element is identified, it adjusts the marginTop property of the parent
> to match the top inset value provided by useSafeAreaInsets, and then clears the interval to stop further execution.
> This approach resolved the issue in my case. I hope it helps others facing similar challenges.

Thank you so much! It works!!
