### ISSUE TITLE
Adding footer component

### ISSUE THREAD

**Issue by Cnilton** [douglasjunior/react-native-recaptcha-that-works#5]
Hi @douglasjunior, thanks for the amazing lib. What about creating a footerComponent prop for this lib? Or at least create a style to then container for using flexDirection: 'column-reverse'.

**Comment by douglasjunior** [comment]
I think that a footerComponent is a better idea.

**Comment by douglasjunior** [comment]
Done in 1.2.0 https://github.com/douglasjunior/react-native-recaptcha-that-works/releases/tag/1.2.0
