### ISSUE TITLE
Creating a site key for android and iOS

### ISSUE THREAD

**Issue by joaombpereira-eng** [douglasjunior/react-native-recaptcha-that-works#51]
To create a siteKey for iOS and Android, do we have to do it through here? https://cloud.google.com/recaptcha-enterprise/docs/create-key-mobile

**Comment by douglasjunior** [comment]
Is not key for Android and iOS, is the key for WEB.

**Comment by joaombpereira-eng** [comment]
So, we choose the Plataform Type: Website?

**Comment by douglasjunior** [comment]
> So, we choose the Plataform Type: Website?

Yes!

> siteKey | string | (Required) Your Web reCAPTCHA site key. (The Web key must be used, not for Android)

**Comment by joaombpereira-eng** [comment]
i'm using the web siteKey and Base Url and isn't working. Return me a error message "null"

<img width="419" alt="Captura de ecrã 2024-03-20, às 11 05 56" src="https://github.com/douglasjunior/react-native-recaptcha-that-works/assets/73299801/9ef85389-8a55-424a-be9e-6fdd180ed623">

**Comment by douglasjunior** [comment]
I notice that you set `enterptise={false}`, but the link of the documentation that you send before was from the reCAPTCHA Enterprise.

If you create the key for reCAPTCHA enterprise, then you need to use `enterprise={true}`

Beyond that, there is nothing else to configure.
