### ISSUE TITLE
[Android] Failed to call method WebViewMessageHandler1.onMessage()

### ISSUE THREAD

**Issue by anisimov74** [douglasjunior/react-native-recaptcha-that-works#53]
Hi! 
 @douglasjunior I got an error message on Android 
`[Android] Failed to call method WebViewMessageHandler1.onMessage(). Module has not been registred as callable`.

react-native": "0.71.11
"react-native-webview": "^13.8.6"

Any ideas why it happens?

Thank you for your efforts.
![Screenshot_20240424_105324](https://github.com/douglasjunior/react-native-recaptcha-that-works/assets/296548/6ebc4c4f-cd9c-44a9-a49c-b18551136775)

**Comment by douglasjunior** [comment]
Hi @anisimov74, probably the auto-linking of `react-native-webview` didn't happen as expected.

Take a look at the`Link native dependencies` section of the `react-native-webview`: https://github.com/react-native-webview/react-native-webview/blob/master/docs/Getting-Started.md#2-link-native-dependencies

**Comment by anisimov74** [comment]
@douglasjunior I solved the problem by cleaning and rebuilding Android project.

**Comment by douglasjunior** [comment]
Nice!
