### ISSUE TITLE
I can't change the style of the recpatcha widget

### ISSUE THREAD

**Issue by pedrokasak** [douglasjunior/react-native-recaptcha-that-works#54]
how can i modify the width of the recpatcha so that i can occupy the entire width of my div and make it so that when the recaptcha is finished the widget doesn't disappear but stays with the checked one, because any modification i make doesn't change the recaptcha widget.

I don't want to use it as a modal, but rather fit it into a form.

**Comment by douglasjunior** [comment]
Ok, so I transferred the issue to the proper repository.

About the `react-native`, the available props are https://github.com/douglasjunior/react-native-recaptcha-that-works?tab=readme-ov-file#props

**Comment by douglasjunior** [comment]
About your initial question: 

> I don't want to use it as a modal, but rather fit it into a form.

Is not possible, because we cant know the size of the WebView, so we need to open it in full screen mode using a Modal.
