### ISSUE TITLE
Only size="invisible" is working when enterprise is true

### ISSUE THREAD

**Issue by alialaa** [douglasjunior/react-native-recaptcha-that-works#55]
I am not sure if this is an issue or maybe an expected behaviour for some reason. When I have enterprise set to true, size normal and compact will not work. The modal will appear for a split second and the on error callback runs with null as the error. But it works normally when size is set to inivisible.

**Comment by douglasjunior** [comment]
Sorry, but I don't know much about reCAPTCHA enterprise.

In this library, when we set `enterprise={true}`, only these changes are set:

https://github.com/douglasjunior/react-native-recaptcha-that-works/blob/cf4607a67b42187acf3b55ae58ab35b0a1a06eda/src/get-template.ts#L44-L50

I can't say why the others sizes don't work.

**Comment by douglasjunior** [comment]
The official documentation says that the `size` are set on the `render` parameters:

- Render: https://cloud.google.com/recaptcha-enterprise/docs/api-ref-checkbox-keys?hl=pt-br#grecaptchaenterpriserender
- Available parameters: https://cloud.google.com/recaptcha-enterprise/docs/api-ref-checkbox-keys?hl=pt-br#attributes_parameters

Is exactly this that we do in the render method:

https://github.com/douglasjunior/react-native-recaptcha-that-works/blob/cf4607a67b42187acf3b55ae58ab35b0a1a06eda/src/get-template.ts#L141-L152

**Comment by alialaa** [comment]
So apparently reCaptcha enterprise is invisible by default unless you choose otherwise when you create the key. I tried another key with this option checked and it worked but of course only when the size prop is not set to invisible. So I guess you can close the issue but maybe add a note in the docs or something. Thank you!

![Screenshot 2024-05-13 at 12 24 43](https://github.com/douglasjunior/react-native-recaptcha-that-works/assets/324106/41cfa87a-3925-447b-8bef-133e74ee120d)

**Comment by douglasjunior** [comment]
Nice catch, thank you for the information!

**Comment by douglasjunior** [comment]
Done!

![image](https://github.com/douglasjunior/react-native-recaptcha-that-works/assets/1512341/b2b58004-5e61-4173-afdd-607683992d33)
