### ISSUE TITLE
reCAPTCHA SDK Update Inquiry

### ISSUE THREAD

**Issue by jintcharadzemar** [douglasjunior/react-native-recaptcha-that-works#56]
Hello,

I'm using your library, [react-native-recaptcha-that-works version 2.0.0] for reCAPTCHA integration in my React Native app. Google has announced a new deprecation and shutdown policy for the reCAPTCHA Mobile SDK: https://cloud.google.com/recaptcha/docs/deprecation-policy-mobile

Could you please let me know which version of the reCAPTCHA SDK is currently used in the library? Additionally, are there any plans to update to the latest SDK to ensure compliance with Google's new policy?

Thank you for your assistance.

Best regards,

Mariam

**Comment by douglasjunior** [comment]
We don't use the Mobile SDK, but the Web v2 https://developers.google.com/recaptcha/docs/display

Btw, thank you for the advice!
