### ISSUE TITLE
Recaptcha always fail

### ISSUE THREAD

**Issue by hassanzadeh** [douglasjunior/react-native-recaptcha-that-works#66]
- What version of React Native?  "0.74.5"
- What version of React Native WebView?  "13.8.6"
- What version of the library? "^2.0.0",
- iOS/Android version? iOS
- Did the problem happen after updating React Native? not working since the beginning
- Are you using the library for the first time? Yes
- It's a bug? Provide a link to a minimal reproduction case.

I'm trying to use this in my expo react native app, and the ref.current.open() always lead to onError call.

```

<ReCaptcha
        ref={captchaRef}
        siteKey={RECAPTCHA_SITE_KEY}
        baseUrl={SITE_URL}
        onVerify={onVerify}
        onError={() => {
          Alert.alert('Error', 'reCAPTCHA failed. Please try again.');
        }}
      />
```

**Comment by douglasjunior** [comment]
It`s working with the online demo right now, please double-check your `siteKey` and `baseUrl`.

Demo: https://snack.expo.dev/@douglasjunior/react-native-recaptcha-that-works

**Comment by yousefturin** [comment]
I just had the same issue, double check both ur baseUrl and siteKey, and make sure the size is invisible in my case is was failing because size was normal or compact. and it worked with invisible.
IOS Simulator 18.2 with react-native=0.74.5, react-native-webview: 13.8.6
