### ISSUE TITLE
New architecture support for React Native 0.76+

### ISSUE THREAD

**Issue by OmkarK45** [douglasjunior/react-native-recaptcha-that-works#68]
Hey! 

Does this library support the new react native architecture? [Link](https://reactnative.dev/architecture/landing-page). 

Sorry to spam issues across your repos 👀 This one is the one I meant to ask on. Cheers

**Comment by douglasjunior** [comment]
This library is JavaScript only, you will need to upgrade the `react-native-webview` to support New Arch.

**Comment by OmkarK45** [comment]
Thanks for confirming!
